### ISSUE TITLE
Not working with ChestSort 

### ISSUE THREAD

**Issue by MTDeath** [kiranhart/Cosmic-Vaults#7]
Thanks for making this, its a great addition to our setup!!

We are using a chest sorting plugin as well but it seems to be incompatible:

https://github.com/JEFF-Media-GbR/ChestSort/issues/144

If you have time (and interest) please see the above link.  
It really makes the vaults more accessible for filling in quantity.

**Comment by kiranhart** [comment]
So essentially you just want to have pvs automatically sorted when they're opened right?

**Comment by MTDeath** [comment]
The Chest sort will sort the chest but will also move items from your inventory to the chest, so if you have one arrow in the chest and a ton of arrows in your inventory, you click outside the Chest gui and it passes all the arrows to the chest in a single click, or click with the other mouse and it sends them all back.  It can also completely clear your (or the chests) inventory by dbl clicking.  
So the Sorting is useful, the mass filling and emptying of the chests is a much more useful aspect of that plugin.

**Comment by kiranhart** [comment]
3.4.0 - Added chestsort support
